library(microbenchmark)

# linear search function generated by ChatGPT 4o
linear_search <- function(arr, target) {
  for (i in 1:length(arr)) {
    if (arr[i] == target) {
      return(i)  # Return index of the found element (1-based index in R)
    }
  }
  return(-1)  # Return -1 if element is not found
}

synth <- sample(1:8192)



# Type your answer to part (a) below these lines, marking each additional line
# as a comment.

target <- synth[1]
timing_data <- microbenchmark(linear_search(synth, target))
print(timing_data)

# Unit: microseconds
#                         expr min  lq   mean median  uq    max neval
# linear_search(synth, target) 1.1 1.2 30.817    1.2 1.2 2961.2   100

# a1. Record the median time, including its units
# Median time: 1.2 microseconds


# a2. Record which of the 100 executions of linear search took the most time.
#     Was the first execution the slowest?
# By viewing the structure of the timing_data, I can see that it has a column
# called "time".

str(timing_data)
# Classes ‘microbenchmark’ and 'data.frame':	100 obs. of  2 variables:
#  $ expr: Factor w/ 1 level "linear_search(synth, target)": 1 1 1 1 1 1 1 ...
#  $ time: num  2961200 2100 1200 1300 1200 ...

# The first number 2961200 seem quite big, but I must somehow find the index
# of the max number in the time column. I will use the max() function.

max_time <- max(timing_data$time)
max_time # 2961200

# Well, I must use the linear search function again to find the index of 
# the max time:

linear_search(timing_data$time, max_time)
# 1

# The function return 1, which means the first execution was the slowest.



# Type your answer to part (b) below these lines, marking each additional line
# as a comment.

target <- tail(synth, n = 1)
timing_data <- microbenchmark(linear_search(synth, target))
print(timing_data)

# Unit: microseconds
#                         expr   min    lq    mean median    uq max neval
# linear_search(synth, target) 296.3 304.4 308.499  305.6 308.1 411   100

# Is the execution you identified as slowest in part (a) again the slowest?

# I will use the linear_search() to find the position of the slowest index:

linear_search(timing_data$time, max(timing_data$time))
# 28

# The answer is no, now the number at the 28th index is the slowest.



# Type your answer to part (c) below these lines, marking each additional line
# as a comment.

# Do your results of parts (a) and (b) support the statement that it is faster
# to locate an element near the start of a list than near the end of a list?

# By comparing the mean time, searching for the first element took 30.817 ms
# while searching for the last element took 308.499 ms. I can say yes to the
# statement that it is faster (308.499 / 30.817 ~ 10 times) to locate an element
# near the start of a list than near the end of a list.
